### ISSUE TITLE
implement filters on queries

### ISSUE THREAD

**Issue by jbuchhammer** [ionos-cloud/ionosctl#106]
### Current SDK Version

```implement filters in ionosctl v5+
```

### Use-cases
IONOS API allows for filtering results (late apply) on resource dependant queries (see https://devops.ionos.com/api/cloud/v5/, Custom Response Filters. Hope link to old SDK doc still works).
This is very useful to get specific resources or requests, e.g. requests being in status QUEUED.

### Proposal
Implement filters for every resource. These are available in CloudAPI but not in ionosctl. They must be implemented in ionosctl too.

**Comment by AnaMariaMoga** [comment]
Hello, 

Thank you for suggesting this enhancement. This was implemented in the latest version of `ionosctl` v6.

Ana
