### ISSUE TITLE
Creating a NAT gateway fails with a sub account user

### ISSUE THREAD

**Issue by mrndev** [ionos-cloud/ionosctl#225]
## Description
Creating a NAT gateway, fails with ionosctl. The command fails with "Internal Server Error" that delivers no information on what went wrong.

## Expected behavior
A NAT gateway can be created with ionosctl and user that is not the contract owner. 

## Environment
```
Go Version: 
mnylund@RancherMaster:~$ go version
go version go1.19.3 linux/amd64

Ionosctl version: 
mnylund@RancherMaster:~$ ionosctl --version
ionosctl version v6.4.3
(installed with snap)
OS: 
mnylund@RancherMaster:~$ lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
Shell: 
Bash
```

## How to Reproduce
create a non-contract-owner user (for example a user that owns just one given DC). try following command to create a NAT
```
 ionosctl natgateway create --datacenter-id $DATACENTERID --ips $PUBLICIP
```

## Error and Debug Output
```
Error: 500 Internal Server Error {
  "httpStatus" : 500,
  "messages" : [ {
    "errorCode" : "301",
    "message" : "Oops! Something went very wrong. Please contact the administrator"
  } ]
}
```
-> the error message should deliver some information why the error happens. "500" implies a bug.

## Additional Notes
- I am able to create the user with the same user in the IONOS GUI
- I am able to run the command with ionosctl version 6.2.0
- (I first had somw wrong information here since i was using to separate installations of ionosctl - information updated now)

**Comment by avirtopeanu-ionos** [comment]
Hi! This should be fixed in v6.5.0 release. Thanks!
