### ISSUE TITLE
ionosctl targetgroup target add requires "--ip/port" - example suggests "--target-ip/port"

### ISSUE THREAD

**Issue by mrndev** [ionos-cloud/ionosctl#261]
## Description
The help text has a small bug
![image](https://user-images.githubusercontent.com/71446193/226902771-727d06d8-21e1-48a4-a917-8fc07838b235.png)

## Expected behavior
consistent help text

## Environment

Ionosctl version: 
ionosctl version v6.5.2

**Comment by avirtopeanu-ionos** [comment]
Thanks, this helps us improve the documentation. I was hoping to one day generate `docopt` compliant examples automatically to avoid maintaining these large lists of examples
