### ISSUE TITLE
"ionosctl k8s nodepool lan list" only shows LanId

### ISSUE THREAD

**Issue by Programie** [ionos-cloud/ionosctl#275]
## Description
Starting with version 6.5.0, `ionosctl k8s nodepool lan list` only prints a single column `LanId`.  The remaining columns `Dhcp`, `RoutesNetwork` and `RoutesGatewayIp` are missing.

## Expected behavior
The command should also show `Dhcp`, `RoutesNetwork` and `RoutesGatewayIp`.

## Environment

Go Version: 
```
6.1.3
```
Ionosctl version: 
```
v6.5.0
```
OS: 
```
Ubuntu 22.04
```
Shell: 
```
zsh
```

## How to Reproduce

1. Download any version >= 6.5.0 of ionosctl, it also happens with the latest version (6.6.1)
2. Execute `ionosctl k8s nodepool lan list --cluster-id <clusterId> --nodepool-id <nodepoolId>`
3. The output only shows a single column (`LanId`)

**Comment by avirtopeanu-ionos** [comment]
Hello, this has been fixed in [release 6.6.2](https://github.com/ionos-cloud/ionosctl/releases/tag/v6.6.2)
