### ISSUE TITLE
`login` doesn't clear previous credentials properly

### ISSUE THREAD

**Issue by arzonus** [ionos-cloud/ionosctl#297]
## Description
If I already have logged using token, and login using username+password, the token won't be cleared.

## Expected behavior
The token has been cleared

## Environment

Go Version:
```
```
Ionosctl version:
```
v6.3.3
```
OS:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

Shell:
```
zsh
```

## Configuration Files
No environment settings

## How to Reproduce
1. `ionosctl login --user username --password password`
2. `ionosctl login --token token`
3. Check config file, the file will contain username+password and token

**Comment by avirtopeanu-ionos** [comment]
Hi! This situation has been improved in v6.7.0: a confirmation check was added which asks you if you'd like to overwrite the existing config file, while previous credentials will be cleared.

Setting `--force` will answer `yes` to this check.

```
 % i login --token $IONOS_TOKEN --skip-verify 
Config file updated successfully. Created the following fields in your config file:
 • token

 % i login --token $IONOS_TOKEN --skip-verify
Config file [...path...] already exists. Do you want to replace it? [y/n]: y
Config file updated successfully. Created the following fields in your config file:
 • token
 
  % i login --user $IONOS_USERNAME --password $IONOS_PASSWORD --force               
Note: Your account has 2 active tokens. Config file updated successfully. Created the following fields in your config file:
 • token
```
