### ISSUE TITLE
Unable to list registries | Unmarshal error on storage usage | Related #320

### ISSUE THREAD

**Issue by xtrcode** [ionos-cloud/ionosctl#326]
## Description
Error on container-registry registry list command

## Expected behavior
List all Registries

## Environment
Installed through snap according to docs: https://docs.ionos.com/cli-ionosctl/

Go Version:
```
$ go version
go version go1.20.5 linux/amd64
```
Ionosctl version:
```
$ ionosctl version
v6.6.4

```
OS:
```
openSUSE Tumbleweed 
Linux ws03 6.4.3-1-default
```
Shell:
```
bash
```

## Configuration Files
Defaults with added login

## How to Reproduce
1. Create registry
2. Push images
3. Login with ionosctl
4. ionosctl cr r list

## Error and Debug Output
$ ionosctl cr r list
Error: json: cannot unmarshal number 8516032228 into Go struct field StorageUsage.items.properties.storageUsage.bytes of type int32

## Additional Notes
Access through cURL is working and showing that the number is the storage usage in bytes
$ curl -u $AUTH --location --request GET 'https://api.ionos.com/containerregistries/registries' --data-raw ''
[...]
"storageUsage":{"bytes":8516032228,"updatedAt":"2023-07-25T06:31:03Z"}
[...]

## References
-

**Comment by xtrcode** [comment]
Same behaveior when using the latest version directly from git and building it locally:
```
$ ./builds/ionosctl_linux_amd64 cr r l     
                       
Error: json: cannot unmarshal number 8516032228 into Go struct field StorageUsage.items.properties.storageUsage.bytes of type int32
```

**Comment by xtrcode** [comment]
Thansk!
When is the release of the commit #320 planned?

**Comment by avirtopeanu-ionos** [comment]
Hey, release [v6.6.5](https://github.com/ionos-cloud/ionosctl/releases/tag/v6.6.5) should fix this

**Comment by xtrcode** [comment]
Can confirm that it works with v6.6.5, thanks for the notice!

**Comment by avirtopeanu-ionos** [comment]
great! have a lovely day
