### ISSUE TITLE
IONOS_API_URL not working since v6.6.4

### ISSUE THREAD

**Issue by maxbischoff** [ionos-cloud/ionosctl#349]
## Description

When using ionosctl v6.6.4 or newer (tested up until 6.6.8), the `IONOS_API_URL` environment variable does not seem to be used anymore.
Instead of accessing the api endpoint configured this way, the variable is ignored and the default value used.

## Expected behavior

I expect the environment variable `IONOS_API_URL` to define the API endpoint accessed by ionosctl, similar to the `--api-url` / `-u` flag.

## Environment

Ionosctl version:
```
6.6.4 (and newer)
```
OS:
```
darwin/arm64
```
Shell:
```
zsh
```

## How to Reproduce

1. Set up `ionosctl` for normal API access, e.g. by exporting the `IONOS_USERNAME` and `IONOS_PASSWORD` env variables
2. Verify that API access works using `ionosctl dc list`
3. Set `export IONOS_API_URL=doesnt.exist` or a similar url that should not work
4. Run `ionosctl dc list`. Observe that the same result as in step 2 is obtained.
5. (optional) run `ionosctl -u $IONOS_API_URL dc list` and observe an error

**Comment by avirtopeanu-ionos** [comment]
Hey, thanks for opening this issue, PR #350 should fix this
