### ISSUE TITLE
bug: image update resets attributes and leads to unexpected behavior 

### ISSUE THREAD

**Issue by hegerdes** [ionos-cloud/ionosctl#359]
## Description

When updating an image name with the ionosctl (`ionosctl image update --image-id xxx --name my-new-name`) it resets other attributes of the image. Like the LicenceType was reset to `UNKNOWN`, even when it was Linux before. Sometimes cloud init gets also reset. The description field on the other hand was not reset.

Making things even worse, it shows inkonsistent information everywhere. The Web GUI response shows totally different attributs

Before the update:
![image](https://github.com/ionos-cloud/ionosctl/assets/40325561/63021f43-c25e-440b-aae0-138595eacfba)

After the update:
![image](https://github.com/ionos-cloud/ionosctl/assets/40325561/d24bb3c4-959b-4891-b6fb-7f59d7a57646)

In the IONOS Web GUI:
![image](https://github.com/ionos-cloud/ionosctl/assets/40325561/1c97660d-23db-434e-a3fd-bb2c6212601a)

## Expected behavior

Update only the fields that should be updated and do not reset others - leading to unexpected behavior.

## Environment

Go Version:
```
None
```
Ionosctl version:
```
ionosctl version v6.6.9
```
OS:
```
Windows 11
```
Shell:
```
bash
```

**Comment by avirtopeanu-ionos** [comment]
Hello! Thanks for opening this issue.

This indeed shouldn't be happening. I've managed to reproduce as well both on `v6.6.9` as well as on an older version, `v6.4.2`.

It seems like the affected fields are all Hot Plug (are set to `true`), all Hot Unplug fields (are set to `false`), as well as the CloudInit support (is set to `V1`) and the mentioned licenseType field being set to `UNKNOWN`.

However I'm not sure about the inconsistency between DCD and the IONOS Cloud API - could you please elaborate as to what's wrong here?

In any case, a patch release will be released soon to include a bugfix for this issue - the image's fields shouldn't be modified if the corresponding flags are not set.

Thank you once again, and have a nice day!

**Comment by hegerdes** [comment]
Great! Happy to here there is a fix on the way.

> However I'm not sure about the inconsistency between DCD and the IONOS Cloud API - could you please elaborate as to what's wrong here?

Please compare the second and third picture. It shows to same uploded image (debian-11-amd64-2023-09-1). In the second picture it shows that is has CloudInit support, but in the DCD it is set to unsupported. Both pictures ware made within a minute or so. I did reload the DCD before taking the screenshot (it often des not reflect the up to date sate of the DC if you work with multiple people or a CI system), still cli and DCD reported different attributes for the same image  for CloudInit.
