### ISSUE TITLE
Flag --no-headers for text output  not working

### ISSUE THREAD

**Issue by urfin78** [ionos-cloud/ionosctl#388]
## Description
The `--no-headers` flag to avoid printing the headers is not working at least for the `datacenter`,`volumes` and `snapshot list` commands. The headers are always printed.

## Expected behavior
don't print the headers

## Environment

Ionosctl version:
```
ionosctl version v6.7.0
```
OS:
```
Ubuntu 22.04.3 LTS
```
Shell:
```
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```

## How to Reproduce
`ionosctl datacenter list --no-headers`

**Comment by avirtopeanu-ionos** [comment]
Hi, sorry for the inconvenience. This should be fixed in v6.7.1. 

As a side note, the `--max-results` flag is now global, meaning that various other commands that might have been missing this flag now should work as expected

Thanks for opening this issue and have a nice day!
