### ISSUE TITLE
Location should show "Available Architectures / CPU Family"

### ISSUE THREAD

**Issue by philipwelz** [ionos-cloud/ionosctl#39]
### Use-cases

If you are using the `terraform-provider-ionoscloud` to create compute instances on IONOS, you have to create a `datacenter` where you have to choose the `location` where the VDC will be created.

For this the `ionosctl location list` command is very useful

Later when you deploy your instances via terraform, you can set the `CPU_FAMILY` for those compute instances. 
Unfortunately not all of the CPU architectures (Intel Syklake, Intel Xeon & AMD Opteron) are available on all locations.

If you for example choose `AMD Opteron` at location `de/fra` your Terrafrom execution will just fail.

To provide a better user experience i have to following proposal: 

### Proposal

Add a `CPU` or `Available Architectures` row to the output of `ionosctl location list`: 

```
LocationId   Name        Features   CPU
de/fra       frankfurt   [SSD]      Intel Syklake
us/las       lasvegas    [SSD]      Intel Xeon, AMD Opteron
us/ewr       newark      [SSD]      Intel Xeon, AMD Opteron
de/txl       berlin      [SSD]      Intel Syklake
gb/lhr       london      [SSD]      Intel Syklake
```

**Comment by AnaMariaMoga** [comment]
In ionosctl version 6.0.0-beta2, this is supported.

```
$ ionosctl datacenter list 
DatacenterId                           Name    Location   CpuFamily                  State
ec644c22-1e82-458c-84cd-bb6ad1bace06   test1   us/las     [AMD_OPTERON INTEL_XEON]   AVAILABLE
eee78109-8730-4d64-85b5-428e8012c65b   test    us/las     [AMD_OPTERON INTEL_XEON]   AVAILABLE

$ ionosctl location list 
LocationId   Name        CpuFamily
de/fra       frankfurt   [INTEL_SKYLAKE]
us/las       lasvegas    [AMD_OPTERON INTEL_XEON]
us/ewr       newark      [AMD_OPTERON INTEL_XEON]
de/txl       berlin      [INTEL_SKYLAKE]
gb/lhr       london      [INTEL_SKYLAKE]
es/vit       logrono     [INTEL_SKYLAKE]
```
