### ISSUE TITLE
Add manpages for ionosctl and docs

### ISSUE THREAD

**Issue by xtrcode** [ionos-cloud/ionosctl#450]
### Current Sdk Version
`ionosctl version v6.7.6`
### Use-cases
It would be great to keep working in terminal, searching through all configuration options is way faster then calling `ionosctl [command] --help` three times to get the needed information.

### Proposal
Please add manpages for ionosctl and preferably the entire [docs](https://docs.ionos.com) (which seem to be just some markdown files), preventing having to switch between browser and cli.

**Comment by glimberea** [comment]
Hi, apologies for the slow response, we will be looking into it and we'll keep you posted.

**Comment by glimberea** [comment]
Added by https://github.com/ionos-cloud/ionosctl/pull/456 and released with [v6.7.8](https://github.com/ionos-cloud/ionosctl/releases/tag/v6.7.8)
