### ISSUE TITLE
Cannot install ionosctl via Homebrew on WSL Debian anymore

### ISSUE THREAD

**Issue by CorentinKirchnerSperi** [ionos-cloud/ionosctl#453]
## Description

I cannot install `ionosctl` with Homebrew on WSL (Windows Subsystem for Linux) anymore.

## Expected behavior

I already installed `ionosctl` successfully in the past with Homebrew on WSL following the description from your [`README.md`](https://github.com/ionos-cloud/ionosctl?tab=readme-ov-file#installing-on-macos) file:

```
brew tap ionos-cloud/homebrew-ionos-cloud
brew install ionosctl
```

## Environment

Go version:
```
go1.21.8 linux/amd64
```

Ionosctl version:
```
v6.7.7
```

Sorry, I do not remember which is the last version of `ionosctl` I installed or updated successfully with Homebrew.
But I noticed that Homebrew does not update or install `ionosctl` anymore around the 2024-05-02.

OS:
```
Debian GNU/Linux 11 (bullseye)
via neoPackage Microsoft Windows Subsystem for Linux 5.10.16
on Windows 11 Enterprise
Version: 23H2
OS build: 22631.3880
Experience: Windows Feature Experience Pack 1000.22700.1020.0
```

Shell:
```
Bash and Fish
```

## Configuration Files

No configuration files.

## How to Reproduce

1. Open the Bash or Fish shell terminal.
2. Execute `brew tap ionos-cloud/homebrew-ionos-cloud`.
3. Get the following output:

```
==> Auto-updating Homebrew...
```

4. Execute `brew install ionosctl`.
5. Get the following output:

```
==> Auto-updating Homebrew...
==> Fetching ionos-cloud/ionos-cloud/ionosctl
==> Downloading https://github.com/ionos-cloud/ionosctl/releases/download/v6.7.7/ionosctl-6.7.7-linux-amd64.tar.gz
Already downloaded: /home/ckirchnersperi/.cache/Homebrew/downloads/2783cda6b8f23b38207ba2055913fd7083f6913c3190fd5d506f7d3d9833907a--ionosctl-6.7.7-linux-amd64.tar.gz
==> Installing ionosctl from ionos-cloud/ionos-cloud
Error: The following formula cannot be installed from bottle and must be
built from source.
  ionosctl
Install Clang or run `brew install gcc`.
```

## Error and Debug Output

See in the "How to Reproduce" paragraph.

## Additional Notes

No additional notes.

## References

No additional references.

**Comment by avirtopeanu-ionos** [comment]
Hi, I'll look into this

In the meantime, seeing as you have `go`, you could install via `go install`: `go install github.com/ionos-cloud/ionosctl/v6@latest`

Thanks for opening this issue, I'll investigate

**Comment by CorentinKirchnerSperi** [comment]
@avirtopeanu-ionos, oh sorry, I found the problem on my computer!

By installing `gcc` with Homebrew via the command:
```
brew install gcc
```
it installs the command `gcc-14` but not `gcc`.

I had then to create a symbolic link myself:
```
ln --symbolic './gcc-14' /home/linuxbrew/.linuxbrew/bin/gcc
```
And then I can install `ionoctl` with Homebrew successfully. 👍

We can close this bug.
Thanks.
