### ISSUE TITLE
Unable to create logging pipeline

### ISSUE THREAD

**Issue by benschmi** [ionos-cloud/ionosctl#457]
## Description
Creating a logging pipeline using the example in the docs or ctl help does not work:
$ ionosctl logging-service pipeline create --name bensLoggingPipeline --log-tag k8s --log-source kubernetes --log-protocol tcp 
Error: 404 Not Found: {"msg": "Not Found"}

## Expected behavior
Creation of logging pipeline

## Environment

Go Version:
```
```
Ionosctl version:
```
$ ionosctl version
v6.7.7
```
OS:
```
$ sw_vers
ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93 
```
Shell:
```
$ echo $SHELL
/bin/zsh
```

## How to Reproduce
```
$ ionosctl logging-service pipeline create --name bensLoggingPipeline --log-tag k8s --log-source kubernetes --log-protocol tcp
```

## Error and Debug Output
```
Error: 404 Not Found: {"msg": "Not Found"}
```

**Comment by glimberea** [comment]
Hello, could you please tell me if you have the `IONOS_API_URL` environment variable set?

**Comment by benschmi** [comment]
The API-Url is set in the config-json:
```
$ cat ${HOME}/Library/Application\ Support/ionosctl/config.json 
{
  "userdata.api-url": "https://api.ionos.com",
...
```

Other commands are also working:
```
 $ ionosctl datacenter list  
DatacenterId                           Name                Location   CpuFamily                                IPv6CidrBlock              State
509d857f-fa55-4efc-8d3e-3d2f8b738498 ...
```

**Comment by glimberea** [comment]
If you remove that line from the config, the logging pipeline command should work. I suggest using `IONOS_API_URL` env var if you ever need to use a specific API URL.

**Comment by benschmi** [comment]
Thanks. Removing it is the solution. I wonder why though, since I never set that property manually but I believe it was auto-generated.

**Comment by glimberea** [comment]
Currently, it gets added to the config file if you run the `ionosctl login` command in the following scenarios:
1. the `--api-url` flag is set
2. the `IONOS_API_URL` env var is set
3. the `userdata.api-url` field is already present in the config file

Now, I cannot know what exactly happened in your case, but I can assume it was one of the three. If there isn't anything else that I can help you with, I will be closing this issue. 

Have a great day!
