### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Exordian** [ionos-cloud/ionosctl#90]
As I couldn't find a license information, I'd kindly ask to consider adding a license file. Without a license [1], it's hard(er) to redistribute ionosctl (e.g. at official linux distribution package repositories).

Your terraform provider is MPL-2.0 [2] licenced.

[1] https://choosealicense.com/no-permission/
[2] https://github.com/ionos-cloud/terraform-provider-ionoscloud/blob/master/LICENSE

**Comment by Exordian** [comment]
FYI: other public repositories in your group are unlicensed as well (SDK repositories, ansible module)

**Comment by AnaMariaMoga** [comment]
Hello, 

Added licenses for SDKs repositories, Ansible Module & CLI.
Thanks for raising awareness. Closing this issue.
